/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package company;

import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.time.LocalDate;
import java.util.Date;
/**
 *
 * @author DELL VOSTRO V131
 */
public class Employee3 extends javax.swing.JFrame {
    
    private String currentUser;
    Connection conn = null;
    PreparedStatement pst = null;
    PreparedStatement pst1 = null;
    ResultSet rs = null;
    /**
     * Creates new form Employee3
     */
    public Employee3() {
        initComponents();
    }
    
    public Employee3(String currentUser) {
        initComponents();
        this.currentUser = currentUser;
    }
    
    public String getUser() {
        return this.currentUser;
    }
    
    public Date convertToDateViaSqlDate(LocalDate dateToConvert) {
        return java.sql.Date.valueOf(dateToConvert);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Job ID", "Salary", "Edra", "Position Title", "Announce Date", "Submission Date", "Evaluator ID", "Company AFM"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText(" Show available jobs");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText(" Fill the Job ID, you want to submit application for:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Enter");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(jButton4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(41, 41, 41)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
        tblModel.setRowCount(0);        
        conn = MySqlConnect.ConnectDB();
        Date date1 = convertToDateViaSqlDate(LocalDate.now());
        String str = getUser();
        String mysql2 = "SELECT comp_AFM FROM employee WHERE username LIKE ?";
        String mysql = "SELECT * FROM job WHERE comp_AFM LIKE ?";
        String c = "";
        try {
            pst = conn.prepareStatement(mysql2);
            pst.setString(1, str);
            rs = pst.executeQuery();
            while (rs.next()) {
                c = rs.getString("comp_AFM");
            }
            
            rs = null;
            
            pst1 = conn.prepareStatement(mysql);
            pst1.setString(1, c);
            rs = pst1.executeQuery();
            while (rs.next()) {
                Date date2 = rs.getDate("submission_date");
                if (date1.before(date2))
                {
                String id = String.valueOf(rs.getInt("jobID"));
                String salary = rs.getString("salary");
                String edra = rs.getString("edra");
                String title = rs.getString("pos_title");
                String adate = rs.getString("announce_date");
                String sdate = rs.getString("submission_date");
                String ideval = rs.getString("IDeval");
                String af = rs.getString("comp_AFM");
                
                String dbData[] = {id, salary, edra, title, adate, sdate, ideval, af};
                tblModel.addRow(dbData);
                }
                
            }

        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String str = getUser();
        this.toBack();
        MenuEmployee mm = new MenuEmployee(str);
        mm.setVisible(true);
        mm.toFront();
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        boolean flag = false;
        boolean flag1 = false;
        boolean flag2 = false;
        Date date1 = convertToDateViaSqlDate(LocalDate.now());
        String jobid = jTextField1.getText();
        int i = Integer.parseInt(jobid); 
        String name = getUser();
        conn = MySqlConnect.ConnectDB();
        String mysql = "INSERT INTO request_evaluation VALUES (?, ?)";
        String sql = "INSERT INTO tempuser(username) VALUES(?)";
        String mysql2 = "SELECT * FROM request_evaluation WHERE employee_usr LIKE ? AND job_ID = ?";
        String mysql1 = "SELECT submission_date, announce_date FROM job WHERE jobID = ?";
        try {
            pst1 = conn.prepareStatement(mysql2);
            pst1.setString(1, name);
            pst1.setInt(2, i);
            rs = pst1.executeQuery();
            
            while(rs.next()) {
                flag = true;
                JOptionPane.showMessageDialog(null, "You have already applied for this job.");
                jTextField1.setText("");
            }
            
            if (flag == false) {
                pst1 = conn.prepareStatement(mysql1);
                pst1.setInt(1, i);
                rs = pst1.executeQuery();
               Date date2 = rs.getDate("submission_date");
               Date date3 = rs.getDate("announce_date");
               
               if (date1.after(date3) && date1.before(date2)) {
                pst = conn.prepareStatement("SELECT comp_AFM FROM job WHERE jobID = ?");
                pst.setInt(1, i);
                rs = pst.executeQuery();
                String afm1 = rs.getString("comp_AFM");
                
                pst = conn.prepareStatement("SELECT comp_AFM FROM employee WHERE username LIKE ?");
                pst.setString(1, name);
                rs = pst.executeQuery();
                String afm2 = rs.getString("comp_AFM");
                
                if (afm1.equals(afm2)) {
                pst = conn.prepareStatement("SELECT job_ID FROM evaluation_grades WHERE job_ID = ? AND employee_usr LIKE ?");
                pst.setInt(1, i);
                pst.setString(2, name);
                rs = pst.executeQuery();
                while (rs.next()) {
                    flag1 = true;
                }
                pst = conn.prepareStatement("SELECT jobID FROM evaluation_result WHERE jobID = ? AND username LIKE ?");
                pst.setInt(1, i);
                pst.setString(2, name);
                rs = pst.executeQuery();
                while (rs.next()) {
                    flag2 = true;
                }
                if (flag1==false && flag2==false) {
                pst = conn.prepareStatement(sql);
                pst.setString(1, name);
                int y = pst.executeUpdate();
                
                pst = conn.prepareStatement(mysql);
                pst.setString(1, name);
                pst.setInt(2, i);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Your job application has been successfully submitted.");
                jTextField1.setText("");
                }
                else {
                    JOptionPane.showMessageDialog(null, "You have already applied for this job.");
                }
                }
               } 
               else {
                   JOptionPane.showMessageDialog(null, "Check the submssion and announce date. You can't apply for this job.");
                   jTextField1.setText("");
               }
            }
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employee3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employee3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employee3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employee3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employee3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
