/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package company;

import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;  
 

/**
 *
 * @author DELL VOSTRO V131
 */
public class Evaluator2 extends javax.swing.JFrame {

    private String currentUser;
    Connection conn = null;   
    PreparedStatement pst = null;
    ResultSet rs = null;
    /**
     * Creates new form Evaluator2
     */
    public Evaluator2() {
        initComponents();
    }
    
    public Evaluator2(String currentUser) {
        initComponents();
        this.currentUser = currentUser;
    }
    
    public String getUser() {
        return this.currentUser;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        date_chooser = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Job ID", "Salary", "Edra", "Position title", "Announce date", "Submission date", "Evaluator ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText(" Show info");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setText("Salary: ");

        jLabel2.setText("Edra: ");

        jLabel3.setText("Position title:");

        jLabel4.setText("Sub date: ");

        jButton4.setText("Enter");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Enter");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Enter");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Enter");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jLabel5.setText("Job ID:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addGap(0, 10, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(jTextField2)
                            .addComponent(jTextField3)
                            .addComponent(date_chooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField8, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                            .addComponent(jTextField7)
                            .addComponent(jTextField5)
                            .addComponent(jTextField6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5)
                            .addComponent(jButton4)
                            .addComponent(jButton6)
                            .addComponent(jButton7))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jButton3)))
                .addGap(24, 24, 24)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton6)))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jButton7)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date_chooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
        tblModel.setRowCount(0);
        conn = MySqlConnect.ConnectDB();
        
        String str = getUser();
        String afm = "";
        String mysql = "SELECT AFM FROM evaluator WHERE eval_usr LIKE ?";
        String mysql1 = "SELECT * FROM job WHERE comp_AFM LIKE ?";
        
        try {
            pst = conn.prepareStatement(mysql);
            pst.setString(1, str);
            rs = pst.executeQuery();
            if (rs.next()) {
                afm = rs.getString("AFM");
            }
            
            pst = conn.prepareStatement(mysql1);
            pst.setString(1, afm);
            rs = pst.executeQuery();
            
            while(rs.next()) {
                int jid = rs.getInt("jobID");
                String id = String.valueOf(jid); 
                int sal = rs.getInt("salary");
                String salary = String.valueOf(sal);
                String edra = rs.getString("edra");
                String title = rs.getString("pos_title");
                String adate = rs.getString("announce_date");
                String sdate = rs.getString("submission_date");
                int evalid = rs.getInt("IDeval");
                String eid = String.valueOf(evalid);
                
                String dbData[] = {id, salary, edra, title, adate, sdate, eid};
                tblModel.addRow(dbData);
            }
        }
        
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String str = getUser();
        this.toBack();
        MenuEvaluator me = new MenuEvaluator(str);
        me.setVisible(true);
        me.toFront();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        conn = MySqlConnect.ConnectDB();
        int i;
        String sal = jTextField1.getText();
        int salary = Integer.parseInt(sal);
        String jid = jTextField5.getText();
        int id = Integer.parseInt(jid); 
        int eid = 0;
        String word = getUser(); 
        String mysql2 = "SELECT * FROM job WHERE jobID = ? AND IDeval = ?";
        String mysql = "UPDATE job SET salary = ? WHERE jobID = ?";
        String sql = "INSERT INTO tempuser(username) VALUES(?)";
        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, word);
            i = pst.executeUpdate();
            
            pst = conn.prepareStatement("SELECT IDeval FROM evaluator WHERE eval_usr LIKE ?");
            pst.setString(1, word);
            rs = pst.executeQuery();
            if (rs.next()) {
                eid = rs.getInt("IDeval");
            }
            
            pst = conn.prepareStatement(mysql2);
            pst.setInt(1, id);
            pst.setInt(2, eid);
            rs = pst.executeQuery();
            
            if (rs.next()) {
                pst = conn.prepareStatement(mysql);
                pst.setInt(1, salary);
                pst.setInt(2, id);
                i = pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "The salary of the job has changed."); 
                jButton3ActionPerformed(evt);
                jTextField1.setText("");
                jTextField5.setText("");
            }
            else {
                JOptionPane.showMessageDialog(null, "The ID of the job you've entered may be wrong. Also, you can change only the  elements of a job, you are in charge of");
            }
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        conn = MySqlConnect.ConnectDB();
        int i;
        String edra = jTextField2.getText();
        String jid = jTextField6.getText();
        int id = Integer.parseInt(jid); 
        String word = getUser(); 
        int eid = 0;
        String mysql2 = "SELECT * FROM job WHERE jobID = ? AND IDeval = ?";
        String mysql = "UPDATE job SET edra LIKE ? WHERE jobID = ?";
        String sql = "INSERT INTO tempuser(username) VALUES(?)";
        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, word);
            i = pst.executeUpdate();
            
            pst = conn.prepareStatement("SELECT IDeval FROM evaluator WHERE eval_usr LIKE ?");
            pst.setString(1, word);
            rs = pst.executeQuery();
            if (rs.next()) {
                eid = rs.getInt("IDeval");
            }
            
            pst = conn.prepareStatement(mysql2);
            pst.setInt(1, id);
            pst.setInt(2, eid);
            rs = pst.executeQuery();
            
            if (rs.next()) {
                pst = conn.prepareStatement(mysql);
                pst.setString(1, edra);
                pst.setInt(2, id);
                i = pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "The edra of the job has changed."); 
                jButton3ActionPerformed(evt);
                jTextField2.setText("");
                jTextField6.setText("");
            }
            else {
                JOptionPane.showMessageDialog(null, "The ID of the job you've entered may be wrong. Also, you can change only the  elements of a job, you are in charge of");
            }
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        conn = MySqlConnect.ConnectDB();
        int i;
        String title = jTextField3.getText();
        String jid = jTextField7.getText();
        int id = Integer.parseInt(jid); 
        int eid = 0;
        String word = getUser(); 
        String mysql2 = "SELECT * FROM job WHERE jobID = ? AND IDeval = ?";
        String mysql = "UPDATE job SET position_title LIKE ? WHERE jobID = ?";
        String sql = "INSERT INTO tempuser(username) VALUES(?)";
        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, word);
            i = pst.executeUpdate();
            
            pst = conn.prepareStatement("SELECT IDeval FROM evaluator WHERE eval_usr LIKE ?");
            pst.setString(1, word);
            rs = pst.executeQuery();
            if (rs.next()) {
                eid = rs.getInt("IDeval");
            }
            
            pst = conn.prepareStatement(mysql2);
            pst.setInt(1, id);
            pst.setInt(2, eid);
            rs = pst.executeQuery();
            
            if (rs.next()) {
                pst = conn.prepareStatement(mysql);
                pst.setString(1, title);
                pst.setInt(2, id);
                i = pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "The position title of the job has changed."); 
                jButton3ActionPerformed(evt);
                jTextField3.setText("");
                jTextField7.setText("");
            }
            else {
                JOptionPane.showMessageDialog(null, "The ID of the job you've entered may be wrong. Also, you can change only the  elements of a job, you are in charge of");
            }
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        conn = MySqlConnect.ConnectDB();
        int i;
        String jid = jTextField8.getText();
        int id = Integer.parseInt(jid); 
        int eid = 0;
        String word = getUser(); 
        SimpleDateFormat sdf = new SimpleDateFormat("yyy-MM-dd");
        String date = sdf.format(date_chooser.getDate());
        String mysql2 = "SELECT * FROM job WHERE jobID = ? AND IDeval = ?";
        String mysql = "UPDATE job SET submission_date = ? WHERE jobID = ?";
        String sql = "INSERT INTO tempuser(username) VALUES(?)";
        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, word);
            i = pst.executeUpdate(); 
            
            pst = conn.prepareStatement("SELECT IDeval FROM evaluator WHERE eval_usr LIKE ?");
            pst.setString(1, word);
            rs = pst.executeQuery();
            if (rs.next()) {
                eid = rs.getInt("IDeval");
            }
            
            pst = conn.prepareStatement(mysql2);
            pst.setInt(1, id);
            pst.setInt(2, eid);
            rs = pst.executeQuery();
            
            if (rs.next()) {
                pst = conn.prepareStatement(mysql);
                pst.setString(1, date);
                pst.setInt(2, id);
                i = pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "The submission date for the specific job has changed."); 
                jButton3ActionPerformed(evt);
                date_chooser.setCalendar(null);
                jTextField8.setText("");
            }
            else {
                JOptionPane.showMessageDialog(null, "The ID of the job you've entered may be wrong. Also, you can change only the  elements of a job, you are in charge of");
            }
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Evaluator2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Evaluator2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Evaluator2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Evaluator2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Evaluator2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser date_chooser;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
